# Generated by Django 4.2.10 on 2024-03-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="product",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="testsite.product",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
        migrations.AlterField(
            model_name="user",
            name="product",
            field=models.ManyToManyField(default=False, to="testsite.product"),
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(default=False, to="testsite.group"),
        ),
    ]
