# Generated by Django 4.2.10 on 2024-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0002_alter_group_product_remove_user_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(
                blank=True, default=False, to="testsite.group"
            ),
        ),
    ]
