# Generated by Django 4.2.10 on 2024-03-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0003_alter_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(blank=True, to="testsite.group"),
        ),
    ]
