# Generated by Django 4.2.10 on 2024-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0004_alter_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(
                blank=True, default="not in group", to="testsite.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="product",
            field=models.ManyToManyField(default="no have", to="testsite.product"),
        ),
    ]
